models:
  - name: fact_transactions
    columns:
      - name: transaction_id
        tests:
          - unique
          - not_null
      - name: customer_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_customer')
              field: customer_key
      - name: amount
        tests:
          - not_null

  - name: dim_customer
    columns:
      - name: customer_key
        tests:
          - unique
          - not_null